### ISSUE TITLE
Circular dependency: brewer2mpl depends on ggplot

### ISSUE THREAD

**Issue by msarahan** [conda-forge/ggplot-feedstock#1]
We had some trouble internally building ggplot, and eventually worked back to this being the issue:

https://github.com/conda-forge/ggplot-feedstock/blob/master/recipe/meta.yaml#L20

It's pretty crazy that ggplot requires all of these things as build-time dependencies.  I don't think it's necessarily ours to fix, but we should be wary of it.

CC @bryevdv

**Comment by ocefpaf** [comment]
I think the next release won't need all those. See https://github.com/yhat/ggplot/commit/792e4294cd8ce820a307e1f66dc43c35ae16ce95

**Comment by jakirkham** [comment]
We could use that commit as a patch if it would make life easier.

**Comment by ocefpaf** [comment]
@msarahan what version of `ggplot` are you building internally?

**Comment by bryevdv** [comment]
I was trying to build `0.9.4`

**Comment by ocefpaf** [comment]
> I was trying to build `0.9.4` 

OK. That is the same we built. (The inconsistent, also fixed in that commit, is that `__init__.py` had `0.9.3`.)

**Comment by pmlandwehr** [comment]
I vote apply as patch for now - but I'm unclear why we wouldn't have seen the same circular issue when the CI was running.

**Comment by msarahan** [comment]
My guess would be that the older ggplot (perhaps from defaults) sufficed to
build brewer2mpl, which then allowed us to build this one.

On Mon, Jun 20, 2016 at 1:46 PM, Peter M. Landwehr <notifications@github.com

**Comment by ocefpaf** [comment]
> My guess would be that the older ggplot (perhaps from defaults) sufficed to
> build brewer2mpl

I don't think so. We did not specify `ggplot` as a dependency in the `brewer2mpl` recipe nor it was downloaded at build time. See https://travis-ci.org/conda-forge/brewer2mpl-feedstock/jobs/138134095#L377

I am guessing this is a red-herring. The run time dependencies are really not needed in `ggplot`, but that does not cause any harm here. Maybe you have another set of dependencies/versions there?

**Comment by jakirkham** [comment]
This is a non-issue at this point as we have passed the troublesome version, right?

**Comment by ocefpaf** [comment]
Closing this. I no longer believe this is an issue. Please re-open if I am wrong.
