### ISSUE TITLE
Python 3.6 package

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda-forge/ggplot-feedstock#11]
Hello,

Would it be possible to rebuild the package for Python 3.6, please?

Best regards,
Sebastian

**Comment by pmlandwehr** [comment]
Thanks for the note! It should be [in progress](https://github.com/conda-forge/ggplot-feedstock/pull/12).

**Comment by sebastian-luna-valero** [comment]
Excellent, many thanks!

**Comment by ocefpaf** [comment]
I believe that #12 fixed this.
